Add excution error result
fosslight/fosslight_reuse pull request #55
Opened 2022-05-26 06:28 UTC by bjk7119

## Description

- Add excution error result

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-05-30 06:13 UTC, soimkim commented on src/fosslight_reuse/_result.py
> +    if result_item._excution_error != "N/A":
if result_item._excution_error != "N/A": -> if result_item._excution_error:

2022-05-30 06:27 UTC, soimkim requested changes

2022-05-30 06:27 UTC, soimkim commented on src/fosslight_reuse/_result.py
> +        error_xml.text = result_item._excution_error
Isn't _execution_error a list?

2022-05-30 06:28 UTC, soimkim commented
@bjk7119 , Please add examples with more than two execution errors to the description in both yaml and xml.

2022-05-30 06:35 UTC, bjk7119 commented on src/fosslight_reuse/_result.py
> +        error_xml.text = result_item._excution_error
yes, execution_error is list type

2022-05-31 00:18 UTC, soimkim approved these changes

2022-05-31 00:18 UTC, soimkim commented
@bjk7119 , Please update xml format in the description.

2022-05-31 04:39 UTC, merged